# Generated by Django 4.2.4 on 2023-09-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(max_length=200),
        ),
    ]
