# Generated by Django 4.2.4 on 2023-09-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Google', 'Google'), ('Fitbit', 'Fitbit')], max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('product_desc', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_name.user')),
            ],
        ),
    ]
