# Generated by Django 4.2.4 on 2023-09-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0008_complaintform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintform',
            old_name='brands',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='complaintform',
            old_name='model',
            new_name='seller',
        ),
    ]
