# Generated by Django 4.2.4 on 2023-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0009_rename_brands_complaintform_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
