# Generated by Django 4.2.4 on 2023-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0010_complaintform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
