# Generated by Django 4.2.4 on 2023-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0011_complaintform_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('note', models.TextField()),
            ],
        ),
    ]
