# Generated by Django 4.2.4 on 2023-10-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0013_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='statu',
            new_name='state',
        ),
    ]
