# Generated by Django 4.2.4 on 2023-10-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0014_rename_statu_checkout_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='amount',
        ),
    ]
