from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('contactus/',views.contactus,name='contactus'),
    path('signup/', views.signup, name= 'signup'),
    path('verify_signup_otp/', views.verify_signup_otp, name='verify_signup_otp'),
    path('login/', views.login, name= 'login'),
    path('logout/', views.logout, name= 'logout'),
    path('user_change_password/', views.user_change_password, name= 'user_change_password'),    
    path('seller_login/', views.seller_login, name= 'seller_login'),
    path('seller_add_product/', views.seller_add_product, name= 'seller_add_product'),
    path('seller_view_product/', views.seller_view_product, name= 'seller_view_product'),
    path('seller_product_details/<int:product_id>/', views.seller_product_details, name= 'seller_product_details'),
    path('seller_edit_product/<int:product_id>/', views.seller_edit_product, name= 'seller_edit_product'),
    path('user_view_product/<slug:product_brand>/', views.user_view_product, name= 'user_view_product'),
    path('user_product_details/<int:product_id>/', views.user_product_details, name= 'user_product_details'),
    path('seller_delete_product/<int:product_id>/', views.seller_delete_product, name= 'seller_delete_product'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name= 'add_to_wishlist'),
    path('wishlist/', views.wishlist, name= 'wishlist'),
    path('del_wishlist_product/<int:product_id>/', views.del_wishlist_product, name= 'del_wishlist_product'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart, name='cart'),
    path('del_cart_product/<int:product_id>/', views.del_cart_product, name='del_cart_product'),
    path('change_qty/',views.change_qty, name='change_qty'),
    path('check/',views.check,name='check'),
    path('complaint_form/',views.complaint_form,name='complaint_form'),
    path('helpdesk/',views.helpdesk,name='helpdesk'),
    path('complain_view/',views.complain_view,name='complain_view'),
    path('delete_complaint/<int:id>/',views.delete_complaint,name='delete_complaint'),
    path('complain_view/',views.complain_view,name='complain_view'),
    path('helpdesk_view/',views.helpdesk_view,name='helpdesk_view'),
    path('delete_helpdesknote/<int:id>/',views.delete_helpdesknote,name='delete_helpdesknote'),
    path('checkout/',views.checkout,name='checkout'),
]